name: Solar System Workflow

on: 
  workflow_dispatch: 
  push:
    branches: 
      - main
      - 'feature/*'
    
env:
    MONGO_URI: ${{ vars.MONGO_URI }}

jobs:
  unit-testing:
    name: Unit Testing
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set Up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install Dependencies
        run: npm install

      - name: Run Unit Tests
        run: npm test