name: Solar System Workflow

on: 
  workflow_dispatch: 
  push:
    branches: 
      - main
      - 'feature/*'
    
env:
    DEBUG_MODE: true
    MONGO_URI: 'mongodb+srv://superuser:superpassword@cluster.f6fyb.mongodb.net/?retryWrites=true&w=majority&appName=Cluster'
    MONGO_USERNAME: ${{ vars.MONGO_USERNAME }}
    MONGO_USERPASSWORD: ${{ secrets.MONGO_PASSWORD }}

jobs:
  unit-testing:
    name: Unit Testing
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set Up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install Dependencies
        run: npm install

      - name: Run Unit Tests
        run: npm test
